services:
  laravel.test:
    ports:
      - '8000:80'    # host port 8000 → container port 80
      - '9003:9003' # Xdebug
    volumes:
      - './:/var/www/html'
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal"

  pgsql:
    ports:
      - '5432:5432'

  mailpit:
    ports:
      - '8025:8025'
